/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom7;

/**
 *
 * @author ADMIN
 */
public class desktop extends javax.swing.JFrame {

    /**
     * Creates new form desktop
     */
    public desktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        kq = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtkq = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCV = new javax.swing.JButton();
        btnDT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Máy tính cơ bản");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Máy Tính Cơ Bản");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        A.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A.setForeground(new java.awt.Color(0, 153, 102));
        A.setText("Số a ");

        B.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B.setForeground(new java.awt.Color(0, 153, 102));
        B.setText("Số b");

        txtA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });

        txtB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCong.setText("Cộng");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnTru.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTru.setText("Trừ");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        btnNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhan.setText("Nhân");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });

        btnChia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChia.setText("Chia");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Giải phương trình bậc 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtkq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkq.setForeground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Kết quả");

        btnCV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCV.setText("Chu vi");
        btnCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCVActionPerformed(evt);
            }
        });

        btnDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDT.setText("Diện Tích");
        btnDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTru)
                                .addGap(18, 18, 18)
                                .addComponent(btnNhan)
                                .addGap(18, 18, 18)
                                .addComponent(btnChia))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(A)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B)
                            .addGap(40, 40, 40)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCV)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDT))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(kq, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(148, 148, 148)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(txtkq, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)
                    .addComponent(btnNhan)
                    .addComponent(btnChia)
                    .addComponent(btnXoa))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCV)
                    .addComponent(btnDT)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(kq)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 0;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        double ketQua = numberA + numberB;
        txtkq.setText(Double.toString(ketQua));
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 0;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        double ketQua = numberA - numberB;
        txtkq.setText(Double.toString(ketQua));
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        txtkq.setText("");
        txtA.setText("");
        txtB.setText("");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 0;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        double ketQua = numberA * numberB;
        txtkq.setText(Double.toString(ketQua));
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 1;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        double ketQua = numberA / numberB;
        txtkq.setText(Double.toString(Math.round(ketQua * 100.0)/100.0));
        if (numberB == 0){
                txtkq.setText("lỗi B = 0");
            } 
    }//GEN-LAST:event_btnChiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 0;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        if (numberA == 0){
            if (numberB == 0) txtkq.setText("vô số nghiệm");
            else txtkq.setText("vô nghiệm");
        } else {
            txtkq.setText(Double.toString(Math.round((-numberB/numberA) * 100.0)/100.0));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCVActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 0;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        double ketQua = numberA*2 + numberB*2;
        if (numberA <= 0 || numberB*2 <=0){
            txtkq.setText("chiều dài,chiều rộng lỗi!");
        } else 
        txtkq.setText(Double.toString(Math.round(ketQua * 1000.0)/1000.0));
    }//GEN-LAST:event_btnCVActionPerformed

    private void btnDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTActionPerformed
        // TODO add your handling code here:
        try {
        Integer.parseInt(txtA.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        try {
        Integer.parseInt(txtB.getText());
        }   
            catch (NumberFormatException e) {
            txtkq.setText("Nhập lỗi");  
        }
        double numberA;
        if (txtA.getText().equalsIgnoreCase("")){
            numberA = 0;
        } else {
            numberA = Double.parseDouble(txtA.getText());
        }
        double numberB ;
        if (txtB.getText().equalsIgnoreCase("")){
            numberB = 0;
        } else {
            numberB = Double.parseDouble(txtB.getText());
        }
        double ketQua = numberA * numberB;
        if (ketQua <= 0){
            txtkq.setText("chiều dài,chiều rộng lỗi!");
        } else 
        txtkq.setText(Double.toString(Math.round(ketQua * 1000.0)/1000.0));
    }//GEN-LAST:event_btnDTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JButton btnCV;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnDT;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kq;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtkq;
    // End of variables declaration//GEN-END:variables
}
